# Generated by Django 4.1.7 on 2023-07-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Allocation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='numero_etudiant_enseignant',
            new_name='numero_utilisateur',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='identifiant',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='mot_de_passe',
        ),
    ]
