# Generated by Django 4.1.7 on 2023-07-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Allocation', '0002_rename_numero_etudiant_enseignant_utilisateur_numero_utilisateur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionsProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_limite', models.DateField()),
            ],
        ),
    ]
