# Generated by Django 4.1.7 on 2023-07-17 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Allocation', '0003_instructionsprojet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('sexe', models.CharField(max_length=1)),
                ('age', models.CharField(max_length=200)),
                ('classe', models.CharField(max_length=200)),
                ('filiere', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='taches/')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('soumis', 'Soumis'), ('corrigé', 'Corrigé'), ('traité', 'Traité'), ('archivé', 'Archivé')], max_length=20)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Allocation.etudiant')),
                ('instructeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Allocation.utilisateur')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjetOuvert',
        ),
    ]
