# Generated by Django 4.2.4 on 2023-08-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Allocation', '0005_delete_instructionsprojet_remove_tache_instructeur_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjetArchive',
        ),
    ]
