# Generated by Django 4.2.4 on 2023-08-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Allocation', '0007_alter_projet_statut_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default=1234, max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='numero_utilisateur',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
