# Generated by Django 4.2.4 on 2023-08-21 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Allocation', '0008_utilisateur_last_login_utilisateur_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='etudiant',
            field=models.ForeignKey(default=None, limit_choices_to={'role': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(limit_choices_to={'role': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='cours_enseignes', to=settings.AUTH_USER_MODEL),
        ),
    ]
