# Generated by Django 4.2.4 on 2023-08-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Allocation', '0011_soumission_notetravail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notetravail',
            name='note',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
